package com.sample
 
import com.sample.DroolsTest.Message;

//This compilation fails because field 'm.status' is not visible, even though we're using MVEL
//and because both 'Message.HELLO' and 'Message.GOODBYE' can't be resolved.
/*
rule "Hello World-Goodbye"
    when
        m : Message( myMessage : message )
        if (m.status == Message.HELLO) break [sayHello]
        else if (m.status == Message.GOODBYE) break [sayGoodbye]
    then
    	System.out.println("Not hello and not Goodbye: " + myMessage);    
    then[sayHello]
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
    then[sayGoodbye]
    	System.out.println( myMessage );
end
*/


//When we switch to a "java" dialect, use 'm.getStatus' and use the actual values of Message.HELLO and Message.GOODBYE, the rule does compile.

rule "Hello World-Goodbye" dialect "java"
    when
        m : Message( myMessage : message )
        if (m.getStatus() == 0) break [sayHello]
        else if (m.getStatus() == 1) break [sayGoodbye]
    then
    	System.out.println("Not hello and not Goodbye: " + myMessage);    
    then[sayHello]
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
    then[sayGoodbye]
    	System.out.println( myMessage );
end


